repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        stages: [ commit, push ]

  - repo: https://github.com/pycqa/isort
    rev: 5.5.4
    hooks:
      - id: isort
        stages: [ commit, push ]

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        stages: [ commit, push ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
    - id: mypy
      stages: [ commit, push ]
      additional_dependencies: [pydantic==1.8.2]

  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: poetry run pytest tests
      language: system
      always_run: false
      pass_filenames: false
      stages: [ push ]

